apiVersion: v1
kind: Pod
metadata:
  name: kube-manual
spec:
  containers:
  - image: rutgerblom/kubia
    imagePullPolicy: Always
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP

