apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: mysql-pass
  literals:
  - password=VMware1!

resources:
- wordpress-namespace,yaml
- wordpress-pv.yaml
- wordpress-pvc.yaml
- mysql-deployment.yaml
- wordpress-deployment.yaml
