apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"labels":{"type":"local"},"name":"pv01"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"5Gi"},"hostPath":{"path":"/mnt/pv01"},"storageClassName":"local-storage"}}
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: "2019-12-23T13:23:24Z"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      type: local
    name: pv01
    resourceVersion: "96773"
    selfLink: /api/v1/persistentvolumes/pv01
    uid: f313ddf6-cdfa-45f9-96ba-edb66556445f
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: mysql-pv-claim
      namespace: demons
      resourceVersion: "96751"
      uid: 2c1134c8-cadf-4941-9818-5f5f4eae641a
    hostPath:
      path: /mnt/pv01
      type: ""
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"labels":{"type":"local"},"name":"pv02"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"5Gi"},"hostPath":{"path":"/mnt/pv02"},"storageClassName":"local-storage"}}
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: "2019-12-23T13:23:30Z"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      type: local
    name: pv02
    resourceVersion: "96770"
    selfLink: /api/v1/persistentvolumes/pv02
    uid: d0d5119a-29f0-4740-86ae-f517dd6ae4ce
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: wp-pv-claim
      namespace: demons
      resourceVersion: "96761"
      uid: 58d032ba-3c4e-492e-bef1-901dff637dc5
    hostPath:
      path: /mnt/pv02
      type: ""
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    volumeMode: Filesystem
  status:
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
